### ISSUE TITLE
Delete temp file once execution is finished

### ISSUE THREAD

**Issue by atulatri** [touchifyapp/sfx#1]
This is a great utility. Thank you for open sourcing it.

Does this tool delete tmp folder after execution has been finished?

**Comment by SomaticIT** [comment]
Thanks for your interest.

No it is not because it reuse it if it can find it to accelerate the startup process.
By default, the temp folder is located in the OS temp directory so it's up to the OS to remove this directory.

Moreover, the sfx process look at the version in the temp directory which allow us to update the directory with a new version while keeping the old process on your desktop for example. The old process will then launch the new version.
